version: '3.8'

networks:
  prod:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx.conf'
    depends_on:
      - frontend
    networks:
      - prod

  frontend:
    build:
      context: ./front
    ports:
      - "4200:4200" # Подключение к порту `4200`
    networks:
      - prod