name: CI/CD Pipeline
on:
  push:
stages: 
  - stage: Backend
    jobs:
      build-backend:
      displayName: 'Сборка Backend'
        runs on: ubuntu-cloud-runner
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Set up Node.js
            uses: actions/setup-node@v2
            with:
              node-version: '20'
          - name: Установка Зависимостей
            run: npm install
            working-directory: ./backend
          - name: Сборка Бэкенда
            run: npm run build
            working-directory: ./backend
    - stage: Frontend
      build-front:
        displayName: 'Сборка Frontend'
        runs on: ubuntu-cloud-runner
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Set up Node.js
            uses: actions/setup-node@v2
            with:
              node-version: '20'
          - name: Установка зависимостей
            run: npm install --legacy-peer-deps
            working-directory: ./front
          - name: Сборка Фронтенда
            run: npm run build
            working-directory: ./front
