name: Интеграция

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - test
jobs:
  build_backend:
    name: Сборка Бэкенда 
    runs-on: ubuntu-latest
    steps:
      - name: Проверка кода
        uses: actions/checkout@v2
      - name: Установвка Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Установка зависимостей
        run: npm install
        working-directory: ./backend
      - name: Проверка Linter
        run: npm run lint
        working-directory: ./backend
      - name: Сбока бэкенда
        run: npm run build
        working-directory: ./backend

  build_frontend:
    runs-on: ubuntu-latest
    name: Сборка Фронтенда
    steps:
      - name: Проверка кода
        uses: actions/checkout@v2
      - name: Установка Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Установка зависимостей
        run: npm install
        working-directory: ./front
      - name: Проверка EsLint
        run: npm run lint
        working-directory: ./front
      - name: Сборка frontend
        run: npm run build --prod
        working-directory: ./front
